$ifndef latin_h
    $define I 1
    $define II 2
    $define III 3
    $define IV 4
    $define V 5
    $define VI 6
    $define VII 7
    $define VIII 8
    $define IX 9
    $define X 10
    $define L 50
    $define C 100
    $define CI 101
    $define M 1000
    $define per for
    $define si if
    $define dum while
    $define donec until
    $define quisque each
    $define confectus continue
    $define cis end
    $define sic
    $define posterus next
    $define nihil null
    $define scribe print
    $define aequalitas eq
    $define atque and
    $define vel or
    $define hoc me
    $define non not
    $define priva abs
    $define decolla int
    $define praecide trim
    $define inde char
    $define numera num
    $define ordo seq
    $define meta len
    $define reperi locate
    $define scinde split
    $define scruta index
    $define excerpe extract
    $define includit include
    $define genus class
    $define privata private
    $define publica public
    $define factorem sub
    $define exi exit
    $define fac do
    $define redde return
    $define derivare shift
    $define ergo then
    $define aliud else
    $define ad to
    $define ab from
    $define removere remove
    $define occasus setting
    $define verum true
    $define falsum false
    $define indefinitus undefined
    $define demutator function
    $define assignari assigned
    $define condicio case
    $define cogito case
    $define cogitare case
    $define incipiunt begin
    $define esse eq
    $define inserere insert
    $define iani void
    $define de
    $define creare create
    $define objectum object
    $define casso destroy
    $define acquiro Get
    $define latin_h 1
$endif
